### ISSUE TITLE
DeleteResources is not an AuthZ Workflow

### ISSUE THREAD

**Issue by kcrosby** [Microsoft/MIMWAL#64] opened 2018-11-13 02:47 UTC
DeleteResources activity wiki page indicates it can be used in an AuthZ workflow, but it is not marked as such (IsAuthorizationActivity=false on AIC).

**Comment by NileshGhodekar** [comment] 2018-11-13 07:43
Hi @kcrosby, there is no plan to change the default activity registration (register.ps1) to make this activity available in the AuthZ workflow during MIMWAL deployment. If this is needed for a particular implementation, one can edit the AIC as you have mentioned. This is also already called out in the [Implementation Guidance](https://github.com/Microsoft/MIMWAL/wiki/Delete-Resources-Activity#implementation-guidance) of the Delete Resources activity. I'm closing this issue as by design as this is viewed as a rare use case.

**Closed by NileshGhodekar** 2018-11-13 07:43 UTC
